### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by encukou** [Yubico/python-yubico#19]
Hello,
I would like to port python-yubico to Python 3, keeping compatibility with Python 2 (preferably 2.6+). Would you be interested in the patches? Anything special I should be aware of?

It seems that most of the work will be breaking circular imports, and figuring out what's text strings and what's bytestrings.

**Comment by dainnilsson** [comment]
Maybe a bit late for this reply, but yeah, we'd absolutely accept a PR for that!
