### ISSUE TITLE
Using e.g. slot1 with HOTP needs replug of yubikey after find_yubikey() was called

### ISSUE THREAD

**Issue by the2nd** [Yubico/python-yubico#27]
Hi,

after calling find_yubikey() it is needed to replug the yubikey to get e.g. slot1 configured for HOTP working again. Without replug a button press does simply nothing.

Is there any method i can call to "reset" the yubikey so that no replug is needed?

regards
the2nd

**Comment by klali** [comment]
Hello,

This is a known limitation when this is used with a pyusb before 1.0.
What happens is that the kernel driver for hid is detached so the configuration API can be used, but the attach function doesn't exist until pyusb >= 1.0.

(https://github.com/Yubico/python-yubico/blob/master/yubico/yubikey_usb_hid.py#L478)

**Comment by the2nd** [comment]
Thanks for your answer. Ill try a newer pyusb version....
