### ISSUE TITLE
reboot yubikey via python call?

### ISSUE THREAD

**Issue by the2nd** [Yubico/python-yubico#28]
Hi,

is it possible to reboot a yubikey via a python call just like it does when its re plugged?

the reason for asking this is because i've implemented a OTPme token type that uses the ssh agent interface of gpg-agent (using yubikeys gpg applet in this case) to allow OTPme logins using standard ssh keys. that works great with my yubikey for PAM logins but when doing e.g. a KDE screen unlock i want to make sure that the yubikey requires the PIN (that is passed from my PAM module to gpg-agent) to sign any ssh message, even if the user has not re plugged its yubikey. my current workaround is to restart gpg-agent on screen unlock but that brings in a annoying delay.

i hope this is the right place to ask this question as i found no mailing list ....

**Comment by dainnilsson** [comment]
No, that's not possible unfortunately. You can configure scdaemon to release the card after a while (which I believe will cause it to require PIN again, on use), see the last post here: http://forum.yubico.com/viewtopic.php?f=26&t=1785
I'm not sure if that fixes your delay issue or not, but it could be worth a shot!
