### ISSUE TITLE
Flag for setting oath-id

### ISSUE THREAD

**Issue by axhoffmann** [Yubico/python-yubico#30]
Hi,

is there a possibility to set the flag for the oath-id like with the ykpersonalize tool: 
`ykpersonalize -1 -ooath-hotp -ooath-id`.

Best Regards
Axel Hoffmann

**Comment by dainnilsson** [comment]
Yes, just set a public id (fixed_string)that is 6 bytes (containing OMP, TT and MUI) when programming the credential, and any wanted configuration flags. The relevant flags are:

OATH_FIXED_MODHEX1  0x10  # First byte in fixed part sent as modhex
OATH_FIXED_MODHEX2  0x40  # First two bytes in fixed part sent as modhex
OATH_FIXED_MODHEX 0x50     # Fixed part sent as modhex
