### ISSUE TITLE
release 1.3.3 on pypi for python 3 compatibility 

### ISSUE THREAD

**Issue by AndCycle** [Yubico/python-yubico#38]
as this project is working with the head version and it doesn't have anything new,

I think it's better to push a py3 problem free version on pypi rather than everyone coming here for head version

**Comment by AndCycle** [comment]
guess I am wrong about this, there's more issue hide in there need to be done for py3
```
  File ".\ykaccess.py", line 100, in write_key
    Cfg.mode_oath_hotp(key)
  File "D:\test\runtime\lib\site-packages\yubico\yubikey_config.py", line 322, in mode_oath_hotp
    self._set_20_bytes_key(secret)
  File "D:\test\runtime\lib\site-packages\yubico\yubikey_config.py", line 539, in _set_20_bytes_key
    if data.startswith(b'h:'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

**Comment by SnijderC** [comment]
Could you please make a new release? This bug was fixed 3 years ago, I want to distribute a python CLI tool that depends on `python-yubico` and it therefore has the same bug..

**Comment by dainnilsson** [comment]
Yes. So sorry for taking so long on this. I'll make time for this either this week or next.

**Comment by dainnilsson** [comment]
Done!
