### ISSUE TITLE
checksum of git tag "python-yubico-1.3.3" have changed since may

### ISSUE THREAD

**Issue by fabiscafe** [Yubico/python-yubico#62]
Hi, i maintain the python-yubico package for Arch Linux.

We recently noticed that the checksum of the git tag python-yubico-1.3.3 have changed. 

On May 2, 2024, 11:33 a.m. UTC [it used to be](https://gitlab.archlinux.org/archlinux/packaging/packages/python-yubico/-/blob/main/PKGBUILD?ref_type=heads#L25)

```
b2sums: c407dc65d5d19cda73f49d4e1944ed96e7fae6861bfdb14b7e48c1e432e015b5370300a698b18948e3cce031852f3bd1c105f23ed4984c2ad7fd3e9ab26eb14b
```

While now it is
```
b2sums: e75c67cd8024ba1769011c4c41d918559ea9edf617f80681c12e75389085de1b94abd8581303d5aed64fb360ec17f9afd7ab8f9e709d5e8e56ab45ee0d2be968
```

I couldn't find anything that have changed or a mention of a re-tag, so I'm here to ask for it. 

+ @dainnilsson you did the tag :wave:

**Comment by dainnilsson** [comment]
The commit hash signed by me has not changed, and is a72e8eddb90da6ee96e29f60912ca1f2872c9aea. This tag was created in February of 2019.

How is the b2sum calculated?

**Comment by fabiscafe** [comment]
Thanks that you've pointed me onto this. If I do it manually it get the "old" checksum.

```
git clone https://github.com/Yubico/python-yubico.git
GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null git -c core.abbrev=no -C "python-yubico" archive --format tar "python-yubico-1.3.3" | b2sum 2>&1
c407dc65d5d19cda73f49d4e1944ed96e7fae6861bfdb14b7e48c1e432e015b5370300a698b18948e3cce031852f3bd1c105f23ed4984c2ad7fd3e9ab26eb14b

```

I already opened another issue against out tooling. Lets see what this is about. Thanks again! :)
